### ISSUE TITLE
Add support for caldav calenders

### ISSUE THREAD

**Issue by njnes** [matoubidou/mutt-itip#4]
I like the ics viewing within mutt and the ability to accept/decline etc. the invitations directly from mutt. But I don't use local calenders, ie how hard would adding caldav support be (just for add/del/upd). Probably go has some libraries to help out.

**Comment by matoubidou** [comment]
I am currently using [vdirsyncer](https://github.com/pimutils/vdirsyncer) to sync multiple calendars with my local machine. Using the mutt plugin accepts / declines into the local calendars and they are synced with their online counterparts again.

I think it would be easily possible to add caldav support. Unfortunately I am currently lacking the time. Feel free to add a PR!

Thx

**Comment by njnes** [comment]
I'll checkout vdirsyncer, but the setup feels a bit error prone. Go isn't (jet) a language I use. But maybe I'll get into this one day.
